package com.pcs.entities;
// Generated 26 Sep, 2018 2:57:25 PM by Hibernate Tools 4.0.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * InstituteCategory generated by hbm2java
 */
@Entity
@Table(name = "institute_category", catalog = "ptutors_db")
public class InstituteCategory implements java.io.Serializable {

	private int instituteCategoriesId;
	private String instituteCategoriesName;

	public InstituteCategory() {
	}

	public InstituteCategory(int instituteCategoriesId) {
		this.instituteCategoriesId = instituteCategoriesId;
	}

	public InstituteCategory(int instituteCategoriesId, String instituteCategoriesName) {
		this.instituteCategoriesId = instituteCategoriesId;
		this.instituteCategoriesName = instituteCategoriesName;
	}

	@Id

	@Column(name = "INSTITUTE_CATEGORIES_ID", unique = true, nullable = false)
	public int getInstituteCategoriesId() {
		return this.instituteCategoriesId;
	}

	public void setInstituteCategoriesId(int instituteCategoriesId) {
		this.instituteCategoriesId = instituteCategoriesId;
	}

	@Column(name = "INSTITUTE_CATEGORIES_NAME", length = 200)
	public String getInstituteCategoriesName() {
		return this.instituteCategoriesName;
	}

	public void setInstituteCategoriesName(String instituteCategoriesName) {
		this.instituteCategoriesName = instituteCategoriesName;
	}

}
